package ru.casualplayer.alfheim.worldgen.tree.dreamwood;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.util.RandomSource;
import net.minecraft.util.valueproviders.IntProvider;
import net.minecraft.world.level.LevelSimulatedReader;
import net.minecraft.world.level.levelgen.feature.configurations.TreeConfiguration;
import net.minecraft.world.level.levelgen.feature.foliageplacers.FoliagePlacer;
import net.minecraft.world.level.levelgen.feature.foliageplacers.FoliagePlacerType;
import ru.casualplayer.alfheim.worldgen.tree.AlfheimFoliagePlacers;

public class DreamwoodFoliagePlacer extends FoliagePlacer {

    public static final Codec<DreamwoodFoliagePlacer> CODEC = RecordCodecBuilder.create(dreamwoodFoliagePlacerInstance ->
                    foliagePlacerParts(dreamwoodFoliagePlacerInstance).and(Codec.intRange(0, 16)
                                    .fieldOf("height").forGetter(fp -> fp.height)).apply(dreamwoodFoliagePlacerInstance, DreamwoodFoliagePlacer::new));

    protected final int height;

    public DreamwoodFoliagePlacer(IntProvider radius, IntProvider offset, int height) {
        super(radius, offset);
        this.height = height;
    }

    @Override
    protected FoliagePlacerType<?> type() {
        return AlfheimFoliagePlacers.DREAMWOOD_FOLIAGE_PLACER.get();
    }

    @Override
    public int foliageHeight(RandomSource random, int asd, TreeConfiguration treeConfig) { return this.height; }

    @Override
    protected boolean shouldSkipLocation(RandomSource random, int localX, int localY, int localZ, int range, boolean isLarge) {
        return false;
    }

    @Override
    protected void createFoliage(LevelSimulatedReader level, FoliageSetter setter, RandomSource random, TreeConfiguration treeConfig, int maxFreeTreeHeight, FoliageAttachment attachment, int height, int radius, int offset) {

        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(1).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(1).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(2).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(2).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(2).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(2).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(2).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(2).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(2).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(2).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(2).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(2).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(2).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(3).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(3).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(3).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(3).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(3).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(3).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(3).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(3).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(3).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(3).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(3).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(14).above(3).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(3).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(3).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(3).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(3).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(3).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(3).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(3).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(3).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(3).south(15));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(4).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(4).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(4).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(4).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(4).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(4).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(4).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(4).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(4).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(4).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(4).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(4).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(4).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(4).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(4).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(14).above(4).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(4).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(4).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(4).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(4).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(4).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(4).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(4).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(4).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(4).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(4).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(4).south(15));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(5).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(5).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(5).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(5).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(5).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(5).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(5).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(5).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(5).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(5).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(5).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(5).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(5).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(5).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(5).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(5).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(5).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(5).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(14).above(5).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(5).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(5).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(5).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(5).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(5).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(5).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(5).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(5).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(5).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(5).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(5).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(5).south(15));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(6).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(6).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(6).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(6).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(6).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(6).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(6).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(6).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(6).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(6).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(6).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(6).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(6).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(6).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(6).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(6).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(6).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(6).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(14).above(6).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(6).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(6).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(6).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(6).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(6).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(6).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(6).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(6).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(6).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(6).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(6).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(6).south(15));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(7).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(7).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(7).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(7).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(7).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(7).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(7).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(7).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(7).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(7).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(7).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(7).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(7).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(7).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(7).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(7).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(7).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(7).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(14).above(7).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(7).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(7).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(7).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(7).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(7).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(7).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(7).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(7).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(7).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(7).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(7).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(7).south(15));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(8).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(8).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(8).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(8).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(8).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(8).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(8).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(8).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(8).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(8).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(8).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(8).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(8).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(8).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(8).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(8).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(8).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(8).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(8).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(8).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(8).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(8).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(8).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(8).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(8).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(8).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(8).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(9).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(8).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(14).above(8).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(8).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(8).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(8).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(8).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(8).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(8).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(8).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(8).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(8).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(8).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(8).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(8).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(8).south(15));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(9).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(9).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(9).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(9).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(9).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(9).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(9).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(9).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(9).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(9).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(9).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(9).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(9).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(9).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(9).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(9).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(9).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(9).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(9).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(9).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(9).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(9).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(9).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(9).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(9).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(9).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(9).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(9).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(9).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(9).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(9).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(9).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(9).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(9).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(9).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(9).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(9).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(9).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(9).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(9).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(9).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(9).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(9).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(9).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(9).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(9).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(9).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(9).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(9).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(9).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(9).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(9).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(9).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(9).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(9).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(9).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(9).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(14).above(9).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(9).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(9).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(9).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(9).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(9).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(9).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(9).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(9).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(9).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(9).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(9).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(9).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(9).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(9).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(9).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(9).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(9).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(9).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(9).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(9).south(15));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(10).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(10).south(0));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(10).south(1));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(10).south(1));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(10).south(1));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(10).south(1));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(10).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(10).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(10).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(10).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(10).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(10).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(10).south(3));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(10).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(10).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(10).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(10).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(10).south(4));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(10).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(10).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(10).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(10).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(10).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(10).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(10).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(10).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(10).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(10).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(10).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(10).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(10).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(10).south(7));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(10).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(10).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(10).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(10).south(8));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(10).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(10).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(10).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(10).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(10).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(10).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(12).above(10).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(13).above(10).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(10).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(10).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(10).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(10).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(10).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(0).above(10).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(10).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(10).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(8).above(10).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(10).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(10).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(10).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(7).above(10).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(10).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(10).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(10).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(10).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(10).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(11).above(10).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(10).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(10).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(10).south(14));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(10).south(15));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(11).south(1));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(11).south(1));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(11).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(11).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(11).south(2));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(11).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(11).south(5));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(3).above(11).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(4).above(11).south(6));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(11).south(9));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(2).above(11).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(11).south(10));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(1).above(11).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(9).above(11).south(11));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(6).above(11).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(11).south(12));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(11).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(10).above(11).south(13));
        tryPlaceLeaf(level, setter, random, treeConfig, attachment.pos().east(5).above(11).south(14));

    }
}
